USB_VID = 0x239A
USB_PID = 0x80DA
USB_PRODUCT = "PCA10040"
USB_MANUFACTURER = "Nordic Semiconductor"

MCU_CHIP = nrf52832

INTERNAL_FLASH_FILESYSTEM = 1


CIRCUITPY_SERIAL_UART = 1
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0

USB = FALSE

CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BUSIO = 1
CIRCUITPY_COUNTIO = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CPERIPHERAL = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_NVM = 0
CIRCUITPY_PIXELBUF  = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 1
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_ULAB = 0
MICROPY_PY_ASYNC_AWAIT = 0

SUPEROPT_GC = 0

# Override optimization to keep binary small
OPTIMIZATION_FLAGS = -Os